{
 "title": "Pi 4 Monitoring",
 "description": "Pi 4 Monitoring",
 "tags": [
  "raspberrypi",
  "pi4",
  "prometheus",
  "node_exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Sampling",
    "query": "5s,10s,30s,1m,5m,15m,30m,1h,2h,1d"
   },
   {
    "name": "node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "expr": "node_thermal_zone_temp" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "singlestat",
   "description": "vcgencmd",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Average CPU usage of all cores",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[2m])) by (kubernetes_node)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Root Usage",
   "type": "gauge",
   "description": "Root file system disk space usage",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Average CPU usage of all cores",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[2m])) by (kubernetes_node)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage percentage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Network traffic received in bytes (positive) versus transmitted (negative)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[2m])"
    },
    {
     "expr": "1 - irate(node_network_receive_bytes_total{device=\"eth0\"}[2m])"
    }
   ]
  }
 ]
}