---
# roles/software/tasks/cloud.yml

- name: install cloud software
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "ansible"
    - "python3-ansible-lint"
    - "kubernetes-client"
  become: yes

- name: ensure http exists (for terraform version fetch)
  dnf:
    name: httpie
    state: present
  become: yes

- name: find latest version of terraform
  shell: |
    set -o pipefail
    http get https://releases.hashicorp.com/terraform/ | awk -F/ '/terraform/ { print $3 }' | head -n 1
  register: latest_terraform_version
  changed_when: false

- name: Terraform version verification
  debug:
    msg: "Terraform version found: {{ latest_terraform_version.stdout }}"

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ latest_terraform_version.stdout }}/terraform_{{ latest_terraform_version.stdout }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  become: yes

- name: install helm (check for updates manually)
  unarchive:
    src: https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz
    dest: /usr/local/bin
    mode: '0755'
    remote_src: yes
    exclude:
      - linux-amd64/LICENSE
      - linux-amd64/README.md
      - linux-amd64/tiller
    extra_opts:
      - --strip-components=1
  become: yes
  register: install_helm

- name: init helm if new install
  command: helm init --client-only
  when: install_helm.changed

- name: install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    owner: root
    mode: '0755'
  become: yes

- name: install minishift
  unarchive:
    src: https://github.com/minishift/minishift/releases/download/v1.34.1/minishift-1.34.1-linux-amd64.tgz
    dest: /usr/local/bin
    owner: root
    mode: '0755'
    remote_src: yes
    exclude:
      - minishift-1.34.1-linux-amd64/LICENSE
      - minishift-1.34.1-linux-amd64/README.adoc
    extra_opts:
      - --strip-components=1
  become: yes

- name: install docker-machine (minishift dependency)
  get_url:
    url: https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-Linux-x86_64
    dest: /usr/local/bin/docker-machine
    owner: root
    mode: '0755'
  become: yes

- name: install docker-machine (minishift dependency)
  get_url:
    url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-centos7
    dest: /usr/local/bin/docker-machine-driver-kvm
    owner: root
    mode: '0755'
  become: yes

# TODO: Remove this at some point
- name: legacy - delete minikube package
  dnf:
    name: minikube
    state: absent
  become: yes
