---
# roles/software/tasks/cloud.yml

- name: install cloud software
  dnf:
    name:
      - "ansible"
      - "python3-ansible-lint"
      - "kubernetes-client"
    state: present
  become: yes

# manually pulling kubectl due to repo versions being too old
# however, kubernetes-client still provides useful docs
- name: find latest version of kubectl
  shell: |
    set -o pipefail
    curl -sL https://storage.googleapis.com/kubernetes-release/release/stable.txt
  register: latest_kubectl_version
  changed_when: false

- name: Kubectl version verification
  debug:
    msg: "Kubectl version found: {{ latest_kubectl_version.stdout }}"

- name: install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ latest_kubectl_version.stdout }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin
    owner: root
    mode: '0755'
  become: yes

#curl -L https://github.com/helm/helm/releases/latest/ | grep -oP -- 'https://get.helm.sh/helm-.*?-linux-amd64.tar.gz' | head -n 1
# \K is lookbehind
- name: find latest version of helm
  shell: |
    set -o pipefail
    curl -sL https://github.com/helm/helm/releases/latest/ | grep -oP -- "Release \Kv[0-9]\.[0-9]{1,2}\.[0-9]{1,2}"
  register: latest_helm_version
  changed_when: false

- name: Helm version verification
  debug:
    msg: "helm version found: {{ latest_helm_version.stdout }}"

- name: install helm
  unarchive:
    src: https://get.helm.sh/helm-{{ latest_helm_version.stdout }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    mode: '0755'
    remote_src: yes
    exclude:
      - linux-amd64/LICENSE
      - linux-amd64/README.md
      - linux-amd64/tiller
    extra_opts:
      - --strip-components=1
  become: yes

- name: install helmfile
  get_url:
    url: https://github.com/roboll/helmfile/releases/latest/download/helmfile_linux_amd64
    dest: /usr/local/bin/helmfile
    owner: root
    mode: '0755'
  become: yes

- name: install minishift
  unarchive:
    src: https://github.com/minishift/minishift/releases/download/v1.34.2/minishift-1.34.2-linux-amd64.tgz
    dest: /usr/local/bin
    owner: root
    mode: '0755'
    remote_src: yes
    exclude:
      - minishift-1.34.1-linux-amd64/LICENSE
      - minishift-1.34.1-linux-amd64/README.adoc
    extra_opts:
      - --strip-components=1
  become: yes

# # If project has a path to latest unversioned unarchived release, or latest github release:
# # https://github.com/<owner/project>/releases/latest/<unversioned name>
# # Install it in /usr/local/bin
# - name: install {{ item.name }} {{ item.version }} to /usr/local/bin
#   get_url:
#     url: "{{ item.url }}"
#     dest: "/usr/local/bin/{{ item.name }}"
#     owner: root
#     mode: '0755'
#   loop:
#     - name: minikube
#       url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
#       version: latest
#     - name: docker-machine
#       url: https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-Linux-x86_64
#       version: v0.16.2
#     - name: docker-machine-driver-kvm
#       url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-centos7
#       version: v0.10.0
#   loop_control:
#     label: "{{ item.name }}"
#   become: yes

# TODO: Remove this at some point
- name: remove minishift and dependencies from /usr/local/bin
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - minishift
    - docker-machine
    - docker-machine-driver-kvm
