---
# roles/software/tasks/hashicorp.yml

- name: find latest version of {{ item }}
  shell: |
    set -o pipefail
    curl -sL https://releases.hashicorp.com/{{ item }}/ | awk -F/ '/{{ item }}/ { print $3 }' | head -n 1
  register: latest_release
  changed_when: false

- name: "{{ item }} version"
  debug:
    msg: "{{ item }} version found: {{ latest_release.stdout }}"

- name: install {{ item }}
  unarchive:
    src: https://releases.hashicorp.com/{{ item }}/{{ latest_release.stdout }}/{{ item }}_{{ latest_release.stdout }}_linux_amd64.zip
    dest: /usr/local/bin/
    owner: root
    mode: '0755'
    remote_src: yes
  become: yes
