---
# roles/software/tasks/media.yml

- name: install media viewers
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "firefox"
    - "firefox-wayland"
    - "youtube-dl"
    - "sxiv"
    - "chromium"
    - "playerctl"
    - "zathura"
    - "zathura-pdf-mupdf"
    - "zathura-zsh-completion"
    - "zathura-bash-completion"
  become: yes

- name: enable rpmfusion free
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  become: yes

- name: install mpv
  dnf:
    name: mpv
    state: present
  become: yes

- name: ensure mpv scripts dir exists
  file:
    path: /etc/mpv/scripts
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: yes

- name: install mpv-mpris
  unarchive:
    src: https://github.com/hoyon/mpv-mpris/releases/download/0.2/mpv-mpris-linux-0.2-x86-64.tar.gz
    dest: "/etc/mpv/scripts"
    mode: "0644"
    owner: root
    group: root
    remote_src: yes
  become: yes
