---
# roles/software/tasks/shell.yml

- name: install zsh
  dnf:
    name: zsh
    state: present
  become: yes

- name: ensure user has shell as zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes
