---
# roles/services/tasks/deluge.yml

- name: install deluge
  dnf:
    name: deluge
    state: present
  become: yes

- name: enable deluge-daemon
  systemd:
    name: deluge-daemon
    state: started
    enabled: yes
  become: yes

# - name: enable deluge-web
#   systemd:
#     name: deluge-web
#     state: started
#     enabled: yes
#   become: yes
