---
# roles/services/tasks/ssh.yml
#
- name: ensure openssh installed
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - openssh-server
    - openssh-clients
  become: yes

- name: prohibit password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
    regex: "^PasswordAuthentication "
  become: yes

- name: prohibit root login
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PermitRootLogin no"
    regex: "^PermitRootLogin "
  become: yes

- name: enable sshd only on core
  systemd:
    name: sshd
    state: started
    enabled: yes
  become: yes
  when: (ansible_hostname == "nyaa-core")
