---
# roles/wireguard/tasks/main.yml

- include: install.yml
  tags: wireguard_install

- include: etc_wireguard.yml
  tags: wireguard_etc_wireguard

- include: nyaa_network.yml
  tags: wireguard_nyaa_network
