---
# roles/libvirt/tasks/winvm.yml

- name: set qemu user to self
  lineinfile:
    path: /etc/libvirt/qemu.conf
    line: "user = \"{{ ansible_user_id }}\""
    regexp: "^#?user = \""
  become: yes
  register: qemu_user

- name: restart libvirtd
  systemd:
    name: libvirtd
    state: restarted
  become: yes
  when: qemu_user.changed

- name: enable virtio repo
  get_url:
    url: https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo
    dest: /etc/yum.repos.d/virtio-win.repo
    owner: root
    mode: '0644'
  become: yes

- name: install virtio-win-latest
  dnf:
    name: virtio-win
    enablerepo: virtio-win-latest
    state: present
  become: yes

- name: iommu in grub
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="intel_iommu=on"'
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="'
  become: yes
