---
# roles/libvirt/tasks/winvm.yml

- name: set qemu user to self
  lineinfile:
    path: /etc/libvirt/qemu.conf
    line: "user = \"{{ ansible_user_id }}\""
    regexp: "^#?user = \""
  become: yes
  register: qemu_user

- name: restart libvirtd
  systemd:
    name: libvirtd
    state: restarted
  become: yes
  when: qemu_user.changed

- name: enable virtio repo
  get_url:
    url: https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo
    dest: /etc/yum.repos.d/virtio-win.repo
    owner: root
    mode: '0644'
  become: yes

- name: install virtio-win-latest
  dnf:
    name: virtio-win
    enablerepo: virtio-win-latest
    state: present
  become: yes

- name: check for iommu in grub (must manually add these to GRUB_CMDLINE_LINUX)
  command: grep 'intel_iommu=on iommu=pt rd.driver.pre=vfio-pci' /etc/default/grub
  register: grub_iommu
  failed_when: grub_iommu.rc != 0
  changed_when: true
  become: yes

- name: regenerate grub
  command: grub2-mkconfig -o /etc/grub2-efi.cfg
  become: yes
  when: grub_iommu.changed

- name: dracut vfio
  copy:
    content: "add_drivers+=\"vfio vfio_iommu_type1 vfio_pci vfio_virqfd\"\n"
    dest: /etc/dracut.conf.d/vfio.conf
  become: yes
  register: dracut_vfio

#   content: "options vfio-pci ids=1002:679a,1002:aaa0\n"
- name: modprobe vfio
  copy:
    content: "options vfio-pci ids=1002:687f,1002:aaf8\n"
    dest: /etc/modprobe.d/vfio.conf
  become: yes
  register: modprobe_vfio

- name: rebuild kernels
  command: dracut -f --regenerate-all
  become: yes
  when: dracut_vfio.changed or modprobe_vfio.changed

- name: enable barrier (synergy)
  firewalld:
    zone: libvirt
    service: synergy
    permanent: yes
    immediate: yes
    state: enabled
  become: yes

# add gpu manually for now
# "sudo setenforce 0" required until I figure out a fix for selinux not allowing qemu to access pulseaudio socket
