repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com/
- name: loki
  url: https://grafana.github.io/loki/charts

releases:
- name: loki
  namespace: monitoring
  chart: loki/loki-stack
  values:
  - loki.persistence.enabled: true
- name: grafana
  namespace: monitoring
  chart: stable/grafana
  force: false
  values:
  - persistence:
      enabled: true
      # https://github.com/helm/charts/pull/17806/files
      # if left empty, chart has empty storageClassName
      # which breaks "upgrade --install"s
      storageClassName: local-path
  - ingress:
      enabled: true
      hosts:
      - nyaa-pi4.lan
      path: /grafana
      annotations:
        traefik.ingress.kubernetes.io/rewrite-target: /
    # if left empty, password gets lost, as it is regenerated on every upgrade
    # but doesn't actually get changed in grafana
  - adminPassword: "foobar"
  - env:
      GF_SERVER_ROOT_URL: http://nyaa-pi4.lan/grafana
      GF_SERVER_DOMAIN: nyaa-pi4.lan
  - plugins:
    - grafana-kubernetes-app
    - grafana-polystat-panel
    - grafana-piechart-panel
    - grafana-clock-panel
    # - grafana-worlmap-panel
    # - neocat-cal-heatmap-panel
    # - jeanbaptistewatenberg-percent-panel
    # - yesoreyeram-boomtable-panel
    # - digiapulssi-breadcrumb-panel
    # - agenty-flowcharting-panel
    # - jdbranham-diagram-panel
    # - raintank-worldping-app
    # - natel-plotly-panel
  - datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://loki:3100
          access: proxy
        - name: Telegraf
          type: influxdb
          access: proxy
          url: http://influxdb:8086
          database: telegraf
- name: prometheus
  namespace: monitoring
  chart: stable/prometheus
  values:
  - kubeStateMetrics:
      image:
        repository: k8s.gcr.io/kube-state-metrics-arm64
        # v1.9.4 seems to be missing for some reason
        # tag: v1.9.4
        tag: v1.8.0
  - nodeExporter:
      image:
        # 2020-02-6 no releases that support thermal_zone yet
        tag: master
  # - server:
  #     ingress:
  #       enabled: true
  #       hosts:
  #       - nyaa-pi4.lan/prometheus
  #       annotations:
  #         traefik.ingress.kubernetes.io/rewrite-target: /
- name: influxdb
  namespace: monitoring
  chart: stable/influxdb
  values:
  - image:
      # Alpine image doesn't seem to support arm64
      tag: 1.7
- name: telegraf
  namespace: monitoring
  chart: stable/telegraf
  values:
  - image:
      # Alpine image doesn't seem to support arm64
      tag: 1.13
  - config:
      outputs:
      #   # Disabled as it seems to break with 503 status code
      # - health:
      #     service_address: "http://:8888"
      #     compares:
      #       field: buffer_size
      #       lt: 5000.0
      #     contains:
      #       field: buffer_size
      - influxdb:
          urls:
          - "http://influxdb:8086"
          database: "telegraf"
      inputs:
      - statsd:
          service_address: ":8125"
          percentiles:
            - 50
            - 95
            - 99
          metric_separator: "_"
          allowed_pending_messages: 10000
          percentile_limit: 1000
      - cpu:
      - net:
      - netstat:
      - file:
          files:
          - /sys/class/thermal/thermal_zone0/temp
          name_override: cpu_temperature
          data_format: value
          data_type: integer
