---
# roles/desktop/tasks/common.yml

- name: common desktop utilities
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - pavucontrol
    - light
    - xclip
    - wl-clipboard
  become: yes

- name: autologin gdm
  lineinfile:
    path: /etc/gdm/custom.conf
    insertafter: '^\[daemon\]'
    line: "AutomaticLoginEnable=True"
    regexp: '^AutomaticLoginEnable='
  become: yes

- name: autologin user gdm
  lineinfile:
    path: /etc/gdm/custom.conf
    insertafter: '^AutomaticLoginEnable=True'
    line: "AutomaticLogin={{ ansible_user_id }}"
    regexp: '^AutomaticLogin='
  become: yes
