---
# roles/desktop/tasks/gnome.yml

- name: install gnome utilities
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - gnome-tweaks
    - dconf-editor
    - NetworkManager-tui
    - seahorse
  become: yes

- name: gsettings - general rules
  command: gsettings set {{ item }}
  changed_when: false
  loop:
    - org.gnome.shell.app-switcher current-workspace-only true
    - org.gnome.desktop.interface clock-show-seconds true
    - org.gnome.desktop.interface clock-show-weekday true
    - org.gnome.desktop.interface gtk-theme "'Adwaita-dark'"
    - org.gnome.desktop.interface show-battery-percentage true
    - org.gnome.desktop.peripherals.touchpad tap-to-click true
    - org.gnome.Weather locations "[<(uint32 2, <('Amsterdam', 'EHAM', true, [(0.91280719879303418, 0.083194033496160544)], [(0.91367986341903151, 0.085812027374152042)])>)>]"
    - org.gnome.GWeather temperature-unit "'centigrade'"
    - org.gnome.desktop.input-sources xkb-options "['compose:ralt']"

- name: get default gnome terminal profile
  shell: gsettings get org.gnome.Terminal.ProfilesList default | tr -d "'"
  changed_when: false
  register: gnome_terminal_default

- name: gsettings - gnome terminal default profile
  command: gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_default.stdout }}/" {{ item }}
  changed_when: false
  loop:
    - use-system-font false
    - font "Monospace 11"
    - use-theme-colors false
    - background-color rgb(0,43,54)
    - foreground-color rgb(131,148,150)
    - palette "['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)', 'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)', 'rgb(147,161,161)', 'rgb(253,246,227)']"

- name: gsettings - power - stationary
  command: gsettings set {{ item }}
  changed_when: false
  loop:
    - org.gnome.settings-daemon.plugins.power power-button-action "'interactive'"
    - org.gnome.settings-daemon.plugins.power idle-dim false
    - org.gnome.desktop.session idle-delay 1800
    - org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type "'nothing'"
    - org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 0
    - org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type "'nothing'"
    - org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 0
  when: (ansible_hostname == "nyaa-core")

- name: gsettings - power - mobile
  command: gsettings set {{ item }}
  changed_when: false
  loop:
    - org.gnome.settings-daemon.plugins.power power-button-action "'suspend'"
    - org.gnome.settings-daemon.plugins.power idle-dim true
    - org.gnome.desktop.session idle-delay 1500
    - org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type "'suspend'"
    - org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 7200
    - org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type "'suspend'"
    - org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 1800
  when: (ansible_hostname == "nyaa-gate") or
        (ansible_hostname == "nyaa-work")
