#!/bin/bash
set -euxo pipefail

help_message() {
  echo 'Brighness control helper script'
  echo
  echo "Usage: $0 <option> [inc/dec amount]"
  echo '          set <percentage>'
  echo
  echo 'Options:'
  echo '  inc     increments brightness by percentage'
  echo '  dec     decrements brightness by percentage'
  echo '  set     sets brightness to percentage'
  echo
  echo 'inc and dec snap to the next multiple of 5 if no amount provided'
}

echoerr() {
  >&2 echo -n -e "\e[34m!Error:\e[39m "
  >&2 echo "$@"
}

if ! [ -d /sys/class/backlight/intel_backlight ]; then
  echoerr "/sys/class/backlight/intel_backlight not found. This host is not supported."
  exit 1
fi;

if [[ -z ${1:-} ]]; then
  echoerr "No arguments given"
  help_message
  exit 1
fi

check_parse() {
  #if ! [[ $1 =~ ^(100\|[[1-9][0-9]\|[9-0])$ ]]; then
  if ! [[ $1 =~ ^([1-9][0-9]|[0-9])$ ]]; then
    echoerr "Amount given is not a valid integer (e.g. 50)"
    exit 1
  fi
}

inc_bright() {
  BRIGHTNESS=$(current_brightness)
  NEW_BRIGHTNESS=$(( BRIGHTNESS + $1 ))
  if (( NEW_BRIGHTNESS > 100 )); then
    set_bright 100
  else
    set_bright ${NEW_BRIGHTNESS}
  fi
}

dec_vol() {
  BRIGHTNESS=$(current_brightness)
  NEW_BRIGHTNESS=$(( BRIGHTNESS - $1 ))
  if (( NEW_BRIGHTNESS < 0 )); then
    set_bright 0
  else
    set_bright ${NEW_BRIGHTNESS}
  fi
}

inc_snap() {
  BRIGHTNESS=$(current_brightness)
  DELTA="$(( 5 - (BRIGHTNESS % 5) ))"
  inc_vol "${DELTA}"
}

dec_snap() {
  BRIGHTNESS=$(current_brightness)
  DELTA="$(( BRIGHTNESS % 5 ))"
  if [[ ${DELTA} == 0 ]]; then
    dec_vol 5
  else
    dec_vol "${DELTA}"
  fi
}

set_bright() {
  MAX_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
  # new value = max * wanted / full
  echo $(( MAX_BRIGHTNESS * $1 / 100)) > /sys/class/backlight/intel_backlight/brightness;
}

current_brightness() {
  MAX_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
  CUR_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness);
  # get max
  # get current
  # calculate percentage
  echo $(( CUR_BRIGHTNESS / MAX_BRIGHTNESS ))
}

case "${1:-}" in
  "inc")
    shift
    if [[ -z ${1:-} ]]; then
      inc_snap
    else
      check_parse "$1"
      inc_bright "$1"
    fi
    ;;
  "dec")
    shift
    if [[ -z ${1:-} ]]; then
      dec_snap
    else
      check_parse "$1"
      dec_bright "$1"
    fi
    ;;
  "set")
    shift
    if [[ -z ${1:-} ]]; then
      echoerr "No percentage provided for set"
      exit 1
    else
      check_parse "$1"
      set_bright "$1"
    fi
    ;;
  *)
    echoerr "$1 is not a valid command"
    help_message
    exit 1
esac
