---
# roles/python_means_python3/tasks/main.yml

- name: ensure python means python3
  file:
    src: /usr/bin/python3
    dest: /usr/local/bin/python
    owner: root
    group: root
    state: link
  become: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int < 31
