---
# roles/media/tasks/core.yml

- name: mount nyaa-store
  mount:
    path: /media/nyaa-store
    src: PARTLABEL=nyaa-store
    fstype: ext4
    state: mounted
  become: yes

- name: mount media-store
  mount:
    path: /media/media-store
    src: PARTLABEL=media-store
    fstype: ext4
    state: mounted
  become: yes

- name: mount winvm (noauto)
  mount:
    path: /media/winvm
    src: PARTLABEL=winvm
    fstype: ntfs
    opts: ro,noauto
    state: present
  become: yes

- name: mount winvm-games (noauto)
  mount:
    path: /media/winvm-games
    src: PARTLABEL=winvm-games
    fstype: ntfs
    opts: ro,noauto
    state: present
  become: yes
