---
- name: desktop configuration
  hosts: managed
  become: no

  roles:
    - role: hostname
      tags: hostname

    - role: media
      tags: media

    - role: git
      tags: git

    - role: software
      tags: software

    - role: wireguard
      tags: wireguard

    - role: desktop
      tags: desktop

    - role: python_means_python3
      tags: python_means_python3

    - role: services
      tags: services

    - role: libvirt
      tags: libvirt
