zstyle :compinstall filename '/home/kitty/.zshrc'

autoload -Uz compinit promptinit

# autocompletion
compinit
zstyle ':completion:*' menu select
setopt COMPLETE_ALIASES

# prompt themes
promptinit
prompt walters

# zle vi mode
bindkey -v

# source pkgfile for archlinux for suggestions on
# where to find missing binaries
DISTRO=$(cat /etc/*-release | grep  DISTRIB_ID= | cut -d= -f2)
if [[ $DISTRO == "Arch" ]]; then
  source /usr/share/doc/pkgfile/command-not-found.zsh
fi

# general useful aliases
alias pubip="wget http://ipinfo.io/ip -qO -" 
alias gitdir="cd /home/$USER/Documents/Git/"
alias vpnup="sudo systemctl start openvpn-client@client"
alias vpndown="sudo systemctl stop openvpn-client@client"
alias cclip="xclip -selection clipboard"
alias clipp="xclip -selection clipboard -o"
alias weather="curl wttr.in"
alias download="curl -O -L -C -"
alias inforet="gitdir; cd fraudprotection/inforetrieve; jupyter notebook"
alias badhorse="traceroute bad.horse"
alias telnetwars="telnet towel.blinkenlights.nl"

# alias backdir="cd /run/media/alev/WesternDrive/backup/ArchRsyncApril21/home/alev"

# go through all folders in $gitdir and fetch + status
function gitdircheck {
  returndir=`pwd`
  gitdir;
  for dir in */; do
    cd $dir;
    printf '%48s\n' | tr ' ' -;
    echo $dir;
    git fetch;
    git status;
    cd ..;
  done
  cd $returndir
}

function gitdirpull {
  returndir=`pwd`
  gitdir;
  for dir in */; do
    cd $dir;
    printf '%48s\n' | tr ' ' -;
    echo $dir;
    git pull;
    cd ..;
  done
  cd $returndir
}

function gitdirclean {
  returndir=`pwd`
  gitdir;
  for dir in */; do
    cd $dir;
    printf '%48s\n' | tr ' ' -;
    echo $dir;
    git clean -xi;
    cd ..;
  done
  cd $returndir
}

# history settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt autocd extendedglob nomatch

# beep is bad, and you should feel bad
unsetopt beep
